### ISSUE TITLE
Bug in the Event-Sync module when joining a breakoutroom

### ISSUE THREAD

**Issue by holema** [jitsi-contrib/prosody-plugins#14]
Today I tested the breakout rooms and I noticed, that breakout rooms leads to a confused event-sync.

Scenario:
4 users joing the conference. All users are registered via the module and a hook is send to the api. correctly
2 users are add to a breakout room. The 2 users leaves the conference and the participanft_left request was send two times.
2 user coming back to the main-room. Here is __no__ participant_joined request to the api.

I think that here are now two possible sollutions:
1. Don`t trigger the leave api when a user leaves to a breakt-room. I would prefere this sollution, if it is possible that prosidy can detect a user who leaves a breakoutroom and then send an api call from the main room.
2. trigger the enter and the leave api, when a user leaves to a breakout room and reenter the main room.

**Comment by shawnchin** [comment]
Hi there. Many thanks for the report.

I'm afraid this module predates the breakout room feature, and has not been updated to account for it.

I'm afk for a few days so can't really look into this. My guess is we just need to account for events from breakout rooms too and trigger similar calls but with a `isBreakout` flag like what JaaS does (https://developer.8x8.com/jaas/docs/webhooks-payload).

**Comment by shawnchin** [comment]
@holema Just raised a PR for this. I've modelled the behaviour after what JaaS does with its Webhooks, so it will be option (2) in your list of suggestions. I've added a section in the README to elaborate further on what to expect when occupants move in an out of breakout rooms.

This approach was the most straight-forward to implement since the plugin simply taps into the underlying muc event hooks and we map those events to API calls. If it were possible to implement (1) from within the module, then the same logic should be possible on the consumer end too; keeping this granular and low-level makes it more versatile for other consumers that may want to interpret the data differently.

I hope this meets your needs.

Thanks again for raising the issue.

**Comment by holema** [comment]
Hello @shawnchin ,

You are great. I will test it tomorrow and give you a feedback.
Thanks a lot for the great effort you do.

Best regards

**Comment by shawnchin** [comment]
@holema did you get a chance to try it out? I'm holding off merging until someone tries it out. Just in case :)

**Comment by holema** [comment]
Hello @shawnchin,

We just checked the plugin and it seems to work. We can see all the events in the log in the correct order, but I have to change my API-endpoints, because there my endpoint is a little bit confused.

I will do this tomorrow, and then I can give you a feedback.

Thanks for the great work.

**Comment by shawnchin** [comment]
@holema did you manage to test this?

**Comment by holema** [comment]
Hello @shawnchin,

I`m so sorry. 
We tested it, and everything works like a charm. 🎉 
I have to fix my endpoints to handle the breakout rooms, but the plugin is great.
Thanks a lot for the effort. 🙏🏻

**Comment by shawnchin** [comment]
Awesome. Thanks for the update. I will merge shortly and close this issue. 🍻
