### ISSUE TITLE
关于脚本自动录制的问题

### ISSUE THREAD

**Issue by 1999LP** [jitsi-contrib/prosody-plugins#25]
你好 我是中国的一名程序员 遇到以下问题请教一下
我的环境是：docker-7882 部署的 ，jibri已经启用并且已经可以正确录制
我已经把mod_jibri_autostart.lua放在了prosody-plugins下
但是我发现：
1./etc/prosody/prosody.cfg.lua 这个文件路径不存在
2.所以我在这个文件里面加了 /config/conf.d/jitsi-meet.cfg.lua
----->Component "conference.meet.mydomain.com" "muc"
  modules_enabled = {
    "jibri_autostart";
  }
我的问题是：重新启动后并不生效 ,我是不是应该创建/etc/prosody/conf.d/meet.mydomain.com.cfg.lua这个路径文件

**Comment by emrahcom** [comment]
Hi @1999LP, could you ask this again in English. I tried to translate it but still unclear for me.

**Comment by shawnchin** [comment]
@1999LP The install instructions provided in the README is for non-docker server deployments, so that's not going to work for you.

I don't use docker, but my _guess_ would be that the docker equivalent would be:
1. Download the `mod_jibri_autostart.lua` into your `prosody-plugins-custom` directory (as created in step 4 [here](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#quick-start)).
2. Enabled that module in prosody by setting the env var `XMPP_MUC_MODULES="jibri_autostart"`

p.s. In the future, if you have questions it might be better to ask in the [community forum](https://community.jitsi.org/) instead of raising a issue ticket.
